### PR TITLE
optimization

### PR DESCRIPTION
**Pull request by Lokimed**

### CODE REVIEW

**Comment by MasterBel2** [comment]
Would be useful if you left a description of what you optimised and how? 
Either way, thanks!

**Comment by Beherith** [comment]
I am also interested in what this does :)

**Comment by Beherith** [comment]
Oh right, it doesnt check all ifs if moving stops :)

**Comment by Lokimed** [comment]
Hi. I will change this commit and do more commentaries.

**Comment by Lokimed** [comment]
1) tab changed to spaces because spaces shows similar in any IDE
2) doesnt check all ifs if moving stops
3) Rewrite function walk. Split this by 4 block. Every block commented

**Pull request closed without merging**
