### PR TITLE
fikkusu no jutsu

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ForbodingAngel** [comment]
That fixed it! Can you tell me how it decides if a mex is an upgrade? Does it just use extractsmetal amount? I tried to figure it out, but I couldn't sort out how it was deciding on if the mex was an upgrade.

**Comment by ForbodingAngel** [comment]
Just checked, and the mex upgrader seems to only notice basic mexes as being upgradeable. Could this be changed so that it checks what units have extractsmetal and then use extractsmetal amount as a guide?

Hopefully that makes some sense.

**Comment by ForbodingAngel** [comment]
Shit, I lied. For some reason the upgrader sees the core armed mex as upgradeable, but not the arm cloaked one.

**Comment by sprunk** [comment]
Because there is no cloaked moho.

**Comment by ForbodingAngel** [comment]
OH SHIT, I see how it works! It just clicked for me. I'm sorry. Thank you for your patience throughout all this. I've been a colossal idiot.

**Comment by sprunk** [comment]
Lines 13 and 14 control whether mexes with traits (stealth, weapons) are upgraded into ones with better extraction but without the traits.

**Comment by ForbodingAngel** [comment]
Ohhh. Wow. I am dense.

Sorry for the comment spam (rip inbox). With this latest, I declare this project ready for action! I'm going to go ahead and make a repo for it in my spring helper projects org. Once again, I cannot thank you enough for all your help. There is absolutely no way I could have done it without you (stating the obvious, but whatever :-)).

**Comment by sprunk** [comment]
Don't forget to remove debug echoes. Let me know if you want to have some other gadgets butchered.

**Comment by ForbodingAngel** [comment]
Yep, thanks for the reminder :-)

And ok haha, I will xD

If you have any interest in replacing spring's transport system with a lua one, that's another project I'm working towards. Azaremoth made a good start but it has some issues. I haven't spent a lot of time on it yet, but it's one that is reasonably high on my list of priorities due to the fact that spring's transport system seems to always be in a state of broken/not-broken/sorta-semi-working-but-broken. It seems that for a lot of these basic things, it is better to replace with lua solutions so that we have more control rather then praying for the functionality to not be broken from release->release.

This is my org for these little projects that I'm working on (this will be 0 use to you, but chickens is retrofitted and in good shape now... I just need to make unit icons for them):
https://github.com/Spring-Helper-Projects

**Pull request merged**
